chore: enable CI on all PRs (#15)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,8 +6,6 @@ on:
     branches:
       - "main"
   pull_request:
-    branches:
-      - "main"
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
@@ -94,3 +92,15 @@ jobs:
       - name: Run tests (Windows User Agent)
         if: matrix.browser == 'chromium'
         run: npm run test:windows
+
+  all-test:
+    name: all
+    needs: test
+    runs-on: ubuntu-latest
+    if: ${{ always() }}
+    steps:
+      - run: |
+          if [[ "${{ needs.test.result }}" != "success" ]]; then
+            echo "Matrix failed"
+            exit 1
+          fi
